### ISSUE TITLE
Docker deployment available?

### ISSUE THREAD

**Issue by haemka** [mwtek/dashboarddataprocessor#1]
Is there any docker deployment available or is it planned to release one?

**Comment by KutSaleh** [comment]
@hbegerau @dmeyers138 ist hier irgendwas in dieser Richtung in Planung? docker deployment wäre für uns sehr hilfreich!

**Comment by FloSeidel** [comment]
In order to dockerize the build stage maybe something like this could be suitable:

I created a directory in which I pulled all three necessary repos. The I created the `Dockerfile.build` File inside the `dashboardataprocessor` folder. In the same folder one would have to place an `application.yaml`. In my root directory I created a `docker-compose.yml`

Dockerfile.build:
```
#
# Build stage
#
FROM maven:3.9.5-amazoncorretto-17 AS build_dashboarddataprocessor
ENV HOME_utilities=/usr/app/utilities
ENV HOME_dashboardlogic=/usr/app/dashboardlogic
ENV HOME_dashboarddataprocessor=/usr/app/dashboarddataprocessor

RUN mkdir -p $HOME_utilities
RUN mkdir -p $HOME_dashboardlogic
RUN mkdir -p $HOME_dashboarddataprocessor

WORKDIR $HOME_utilities
ADD utilities $HOME_utilities
RUN --mount=type=cache,target=/root/.m2 mvn -f $HOME_utilities/pom.xml clean install

WORKDIR $HOME_dashboardlogic
ADD dashboardlogic $HOME_dashboardlogic
RUN --mount=type=cache,target=/root/.m2 mvn -f $HOME_dashboardlogic/pom.xml clean install

WORKDIR $HOME_dashboarddataprocessor
ADD dashboarddataprocessor $HOME_dashboarddataprocessor
RUN --mount=type=cache,target=/root/.m2 mvn -f $HOME_dashboarddataprocessor/pom.xml clean install


#
# Package stage
#
FROM openjdk:17 AS dashboard-data-processor
# COPY dashboarddataprocessor/target/dashboarddataprocessor-0.5.0.jar /dashboarddataprocessor/dashboard-data-processor.jar
ARG JAR_FILE=/usr/app/dashboarddataprocessor/target/*.jar
COPY --from=build_dashboarddataprocessor $JAR_FILE /dashboarddataprocessor/dashboard-data-processor.jar

# removed in order to mount it at runtime
# COPY dashboarddataprocessor/application.yaml /dashboarddataprocessor

ENTRYPOINT ["java","-jar","/dashboarddataprocessor/dashboard-data-processor.jar","--spring.config.location=/dashboarddataprocessor/application.yaml"]
```

docker-compose.yml:
```
version: '3.4'

services:
  dashboard-data-processor:
    # image: dashboard-data-processor:0.5.0
    build:
      context: .
      dockerfile: ./dashboarddataprocessor/Dockerfile.build
    container_name: dashboard-data-processor
    restart: always
    ports:
      - '9091:9091'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "20"
    volumes:
      - type: bind
        source: ./dashboarddataprocessor/application.yaml
        target: /dashboarddataprocessor/application.yaml
        read_only: true
```

All of that can of course be optimized by using smaller images and mounting needed external files (keystores, truststores, ...).
